version: '3.8'

services:
  app:
    build: .
    container_name: password-manager-cli
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DB_URL=jdbc:postgresql://db:5432/userlist_db_cli
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres

  db:
    image: postgres:latest
    container_name: postgres-cli-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: userlist_db_cli
    ports:
      - "5432:5432"
    networks:
      - password-manager-network

networks:
  password-manager-network:
    driver: bridge
